version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats
      - DB_HOST=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    volumes:
      - ./init/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - /var/lib/postgresql/data/

  ewm-service:
    build: ewm-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - DB_NAME=service
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
      - SERVICES_STATSERVICE_URI=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    volumes:
      - ./init/schema_service.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - /var/lib/postgresql/data/