version: '3.1'
services:

  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats


  stats-db:
    image: postgres:15.0
    container_name: db-stats
    ports:
        - "6541:5432"
    environment:
        - POSTGRES_DB=stats
        - POSTGRES_USER=stat
        - POSTGRES_PASSWORD=stat
    volumes:
      - /var/lib/postgresql/data/


  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/service


  ewm-db:
    image: postgres:15.0
    container_name: db-ewm-service
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    volumes:
      - /var/lib/postgresql/data/